"""init

Revision ID: 0001
Revises: 
Create Date: 2024-04-05 08:28:25.780156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TotalDistribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aix_processed', sa.DECIMAL(precision=100, scale=0), server_default='0', nullable=True),
    sa.Column('aix_distributed', sa.DECIMAL(precision=100, scale=0), server_default='0', nullable=True),
    sa.Column('eth_bought', sa.DECIMAL(precision=100, scale=0), server_default='0', nullable=True),
    sa.Column('eth_distributed', sa.DECIMAL(precision=100, scale=0), server_default='0', nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TotalDistribution')
    # ### end Alembic commands ###
